FROM python:3.7.10
WORKDIR /src

ENV FLASK_APP=api.py
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_ENV=development
# COPY ./src /src
COPY src/requirements.txt requirements.txt
RUN pip install -r requirements.txt
CMD ["flask", "run"]